#!/bin/sh
# This script is only used for developement. It is removed by the 
# distribution process. 

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -tag debug -classic-display \
                          -use-ocamlfind"}

action () 
{
    case $1 in
      default)      $OCAMLBUILD remat.native ;;
      tests)        echo "No tests for now" ;;
      doc)          shift; action doc-remat $* ;;
      doc-user)     shift; pkg/markdown $* doc/user-doc.css doc/howto.md \
                    doc/describe.md doc/api.md ;;
      doc-remat)    shift; pkg-doc $* doc/remat.docdir ;;
      doc-rematd)   shift; pkg-doc $* doc/rematd.docdir ;;
      remat)        shift; $OCAMLBUILD $* remat.native ;;
      rematd)       shift; $OCAMLBUILD $* rematd.native ;;
      clean)        $OCAMLBUILD -clean ;;
      *)            $OCAMLBUILD $* ;;
    esac
} 

if [ $# -eq 0 ]; 
then action default ; 
else action $*; fi
